# ðŸš¨ Bandit Full Scan Report
* File: ./bbone/pf9app/pf9app/pf9_app.py
  â€¢ Line: 51
  â€¢ Severity: HIGH
  â€¢ Confidence: HIGH
  â€¢ Issue: subprocess call with shell=True identified, security issue.

* File: ./janitor/janitor/__init__.py
  â€¢ Line: 64
  â€¢ Severity: HIGH
  â€¢ Confidence: HIGH
  â€¢ Issue: subprocess call with shell=True identified, security issue.

* File: ./janitor/janitor/glance_cleanup.py
  â€¢ Line: 32
  â€¢ Severity: HIGH
  â€¢ Confidence: HIGH
  â€¢ Issue: Call to requests with verify=False disabling SSL certificate checks, security issue.

* File: ./janitor/janitor/utils.py
  â€¢ Line: 30
  â€¢ Severity: HIGH
  â€¢ Confidence: HIGH
  â€¢ Issue: Call to requests with verify=False disabling SSL certificate checks, security issue.

* File: ./janitor/janitor/utils.py
  â€¢ Line: 42
  â€¢ Severity: HIGH
  â€¢ Confidence: HIGH
  â€¢ Issue: Call to requests with verify=False disabling SSL certificate checks, security issue.

* File: ./janitor/janitor/utils.py
  â€¢ Line: 54
  â€¢ Severity: HIGH
  â€¢ Confidence: HIGH
  â€¢ Issue: Call to requests with verify=False disabling SSL certificate checks, security issue.

* File: ./resmgr/resmgr/dbutils.py
  â€¢ Line: 31
  â€¢ Severity: HIGH
  â€¢ Confidence: HIGH
  â€¢ Issue: The pyCrypto library and its module AES are no longer actively maintained and have been deprecated. Consider using pyca/cryptography library.

